language: php

php:
  - 5.4

mysql:
  database: dcy2014
  username: root
  encoding: utf8

install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database dcy2014;'"

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:6.*

  # Build Behat dependencies
  - cd ./sites/all/tests/behat
  - composer install --no-interaction
  - cd ../../../..

  # Setup files
  - sudo chmod -R 777 sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
  - java -jar selenium-server-standalone-2.39.0.jar > /dev/null 2>&1 &
  - sleep 5

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Install Profile
  - drush si dcy2014_kickstart --db-url=mysql://root:@127.0.0.1/dcy2014 --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Drupalcamp Yorkshire 2014 Install Profile" --yes

  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - sleep 3
  - cd sites/all/tests/behat

script:

  # Run behat tests
  - ./bin/behat --config behat.travis.yml --tags='~@develop'
