language: php

php:
  - 5.4

mysql:
  database: dcy2014
  username: root
  encoding: utf8

install:

  # Create MySQL Database
  - mysql -e 'create database dcy2014;'
  - sudo apt-get --quiet=2 install apache2 libapache2-mod-php5 php5-cli php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:6.*

  # Run composer
  - cd sites/all/tests/behat
  - composer install --no-interaction --prefer-source

  # Going back
  - cd ../../../..

  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Install Profile
  - sudo chmod -R 777 sites/all
  - mkdir -p sites/default/files
  - sudo chmod -R 777 sites/default/files
  - drush si dcy2014_kickstart --sites-subdir=default --db-url=mysql://root:@127.0.0.1/dcy2014 --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Drupalcamp Yorkshire 2014 Install Profile" --yes
  - drush updatedb -y || true
  - drush cc all

  # configure apache virtual hosts
  - sudo cp -f sites/all/tests/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - cat /etc/apache2/sites-available/default
  - sleep 5s

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Prepare tests/behat/behat.local.yml
  - sudo cp -f sites/all/tests/build/travis-ci-behat-yml sites/all/tests/behat/behat.local.yml
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place sites/all/tests/behat/behat.local.yml
  - cat sites/all/tests/behat/behat.local.yml

  # Get Selenium
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
  - java -jar selenium-server-standalone-2.39.0.jar > /dev/null 2>&1 &
  - sleep 5

  - cd sites/all/tests/behat

script:

  # Run behat tests
  - ./bin/behat --tags '~@develop'
  - cd ../../../..
